### ISSUE TITLE
[error]Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ghotm** [Elem8100/MapleNecrocer#28]
Hi, I encountered an issue while using the program, and the error message is as follows: Object reference not set to an instance of an object.
Client download link: https://mega.nz/file/GHRwWI5R#7av149UhIOdqF2yu8TgUQH3GTN7CvvQ9ubzW5Ebkv54

![image](https://github.com/Elem8100/MapleNecrocer/assets/11214172/675f8093-1f5e-47b8-be7c-65afc8390758)

```
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleNecrocer.MainForm.DumpMapIDs() in E:\MapleNecrocer\MapleNecrocer\MainForm.cs:line 110
   at MapleNecrocer.SelectFolderForm.SelectFolderButton_Click(Object sender, EventArgs e) in E:\MapleNecrocer\MapleNecrocer\SelectFolderForm.cs:line 123
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Private.CoreLib.dll
----------------------------------------
MapleNecrocer
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/MapleNecrocer.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.2924.17106
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.2924.17106
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/System.Drawing.Common.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.ComponentModel.TypeConverter.dll
----------------------------------------
WzComparerR2.WzLib
    程序集版本:2.2.0.0
    Win32 版本:2.2.0.10725
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/WzComparerR2.WzLib.dll
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/mscorlib.dll
----------------------------------------
WzComparerR2.PluginBase
    程序集版本:2.2.0.0
    Win32 版本:2.2.0.10725
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/WzComparerR2.PluginBase.dll
----------------------------------------
WzComparerR2.Common
    程序集版本:2.2.0.0
    Win32 版本:2.2.0.10725
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/WzComparerR2.Common.dll
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:6.0.2924.17106
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.2924.17106
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.2924.17106
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Memory.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.ComponentModel.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.ObjectModel.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Linq.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Private.Uri.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.29/System.Resources.Extensions.dll
----------------------------------------
MonoGame.Forms.DX
    程序集版本:2.4.0.0
    Win32 版本:2.4.0.0
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/MonoGame.Forms.DX.dll
----------------------------------------
MonoGame.Framework
    程序集版本:3.8.0.1641
    Win32 版本:3.8.0.1641
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/MonoGame.Framework.dll
----------------------------------------
SharpDX.DXGI
    程序集版本:4.0.1.0
    Win32 版本:4.0.1
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/SharpDX.DXGI.dll
----------------------------------------
SharpDX.Direct3D11
    程序集版本:4.0.1.0
    Win32 版本:4.0.1
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/SharpDX.Direct3D11.dll
----------------------------------------
ManagedBass
    程序集版本:3.1.0.0
    Win32 版本:3.1.0.0
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/ManagedBass.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Collections.NonGeneric.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Collections.Concurrent.dll
----------------------------------------
CharaSimResource
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/CharaSimResource.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Diagnostics.Process.dll
----------------------------------------
SharpDX
    程序集版本:4.0.1.0
    Win32 版本:4.0.1
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/SharpDX.dll
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Text.RegularExpressions.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Core.dll
----------------------------------------
SharpDX.Direct2D1
    程序集版本:4.0.1.0
    Win32 版本:4.0.1
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/SharpDX.Direct2D1.dll
----------------------------------------
SharpDX.Mathematics
    程序集版本:4.0.1.0
    Win32 版本:4.0.1
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/SharpDX.Mathematics.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
DevComponents.DotNetBar2
    程序集版本:12.5.0.2
    Win32 版本:12.5.0.2
    代码库:file:///F:/Games/%E7%BD%91%E6%B8%B8%E5%8D%95%E6%9C%BA%E7%AB%AF/%E5%86%92%E9%99%A9%E5%B2%9B/%E6%BA%90%E7%A0%81/v083%E5%AE%A2%E6%88%B7%E7%AB%AF/MapleNecrocer_20240124/DevComponents.DotNetBar2.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Reflection.Primitives.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.2924.17105
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.29/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************
```

**Comment by Elem8100** [comment]
Please don't use  modified version of wz file. This  tool doesn't work with that. You must  use clean official wz file.

or try MapleStoryGM select GMS(old)
 ![Image 1](https://github.com/Elem8100/MapleNecrocer/assets/49195287/91164891-dd7f-4010-986d-5fc86c832969)
https://github.com/Elem8100/MapleStory-GM-Client/releases/download/v4.1/MapleStoryGM.v4.1.zip

**Comment by ghotm** [comment]
Thank you, the tool is working.

> Please don't use modified version of wz file. This tool doesn't work with that. You must use clean official wz file.
> 
> or try MapleStoryGM select GMS(old) ![Image 1](https://private-user-images.githubusercontent.com/49195287/328164641-91164891-dd7f-4010-986d-5fc86c832969.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzY1OTcsIm5iZiI6MTcxNTE3NjI5NywicGF0aCI6Ii80OTE5NTI4Ny8zMjgxNjQ2NDEtOTExNjQ4OTEtZGQ3Zi00MDEwLTk4NmQtNWZjODZjODMyOTY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDEzNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZTU1Y2M0ZWMzMGNlMzNiNWM1OTlmNWM5YWMyYmIwNzE4YjUxZTFhZDQwYTM4NDBmNDE0NjE2MTA0Zjc0ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-sotfVfvNA9hMecoLidUJ6IGDRqbF92xZ1avdq2ZztQ) https://github.com/Elem8100/MapleStory-GM-Client/releases/download/v4.1/MapleStoryGM.v4.1.zip
