### ISSUE TITLE
TMS 幸福的夢的空間 錯誤訊息

### ISSUE THREAD

**Issue by yotv2000tw** [Elem8100/MapleNecrocer#31]
TMS中 `幸福的夢的空間(993236200~993236205)` 讀取時都會跳出如下錯誤，不知道是否是我的設定有問題：
```
如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WzComparerR2.Animation.SpineAnimator.Load()
   at MapleNecrocer.Obj.Create() in E:\MapleNecrocer\MapleNecrocer\Client\MapObj.cs:line 54
   at MapleNecrocer.Map.LoadMap(String ID) in E:\MapleNecrocer\MapleNecrocer\Client\MapleMap.cs:line 198
   at MapleNecrocer.MainForm.LoadMap() in E:\MapleNecrocer\MapleNecrocer\MainForm.cs:line 757
   at MapleNecrocer.MainForm.LoadMapButton_Click(Object sender, EventArgs e) in E:\MapleNecrocer\MapleNecrocer\MainForm.cs:line 868
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** 已載入的組件 **************
System.Private.CoreLib
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.CoreLib.dll
----------------------------------------
MapleNecrocer
    組件版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/MapleNecrocer.dll
----------------------------------------
System.Runtime
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    組件版本: 6.0.2.0
    Win32 版本: 6.0.1623.17402
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    組件版本: 6.0.2.0
    Win32 版本: 6.0.1623.17402
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Drawing.Common.dll
----------------------------------------
System.Threading
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.dll
----------------------------------------
System.ComponentModel.TypeConverter
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.TypeConverter.dll
----------------------------------------
WzComparerR2.WzLib
    組件版本: 2.2.0.0
    Win32 版本: 2.2.0.10725
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/WzComparerR2.WzLib.dll
----------------------------------------
mscorlib
    組件版本: 4.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/mscorlib.dll
----------------------------------------
WzComparerR2.PluginBase
    組件版本: 2.2.0.0
    Win32 版本: 2.2.0.10725
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/WzComparerR2.PluginBase.dll
----------------------------------------
WzComparerR2.Common
    組件版本: 2.2.0.0
    Win32 版本: 2.2.0.10725
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/WzComparerR2.Common.dll
----------------------------------------
System.Drawing
    組件版本: 6.0.2.0
    Win32 版本: 6.0.1623.17402
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Threading.Thread.dll
----------------------------------------
Accessibility
    組件版本: 4.0.0.0
    Win32 版本: 6.0.1623.17402
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.Loader
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    組件版本: 6.0.2.0
    Win32 版本: 6.0.1623.17402
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/zh-Hant/System.Windows.Forms.resources.dll
----------------------------------------
System.Memory
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Memory.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ComponentModel.dll
----------------------------------------
System.ObjectModel
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.ObjectModel.dll
----------------------------------------
System.Linq
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Linq.dll
----------------------------------------
System.Private.Uri
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Private.Uri.dll
----------------------------------------
System.Resources.Extensions
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.16/System.Resources.Extensions.dll
----------------------------------------
MonoGame.Forms.DX
    組件版本: 2.4.0.0
    Win32 版本: 2.4.0.0
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/MonoGame.Forms.DX.dll
----------------------------------------
MonoGame.Framework
    組件版本: 3.8.0.1641
    Win32 版本: 3.8.0.1641
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/MonoGame.Framework.dll
----------------------------------------
SharpDX.DXGI
    組件版本: 4.0.1.0
    Win32 版本: 4.0.1
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/SharpDX.DXGI.dll
----------------------------------------
SharpDX.Direct3D11
    組件版本: 4.0.1.0
    Win32 版本: 4.0.1
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/SharpDX.Direct3D11.dll
----------------------------------------
ManagedBass
    組件版本: 3.1.0.0
    Win32 版本: 3.1.0.0
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/ManagedBass.dll
----------------------------------------
System.Collections.NonGeneric
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.NonGeneric.dll
----------------------------------------
System.Collections.Concurrent
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Concurrent.dll
----------------------------------------
CharaSimResource
    組件版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/CharaSimResource.dll
----------------------------------------
System
    組件版本: 4.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.dll
----------------------------------------
System.Diagnostics.Process
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.Process.dll
----------------------------------------
SharpDX
    組件版本: 4.0.1.0
    Win32 版本: 4.0.1
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/SharpDX.dll
----------------------------------------
System.Text.RegularExpressions
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Text.RegularExpressions.dll
----------------------------------------
System.Core
    組件版本: 4.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Core.dll
----------------------------------------
SharpDX.Direct2D1
    組件版本: 4.0.1.0
    Win32 版本: 4.0.1
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/SharpDX.Direct2D1.dll
----------------------------------------
SharpDX.Mathematics
    組件版本: 4.0.1.0
    Win32 版本: 4.0.1
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/SharpDX.Mathematics.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
DevComponents.DotNetBar2
    組件版本: 12.5.0.2
    Win32 版本: 12.5.0.2
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/DevComponents.DotNetBar2.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Primitives.dll
----------------------------------------
System.IO.Compression
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.IO.Compression.dll
----------------------------------------
spine-monogame
    組件版本: 1.0.0.1
    Win32 版本: 1.0.0.1
    程式碼基底: file:///C:/Users/User/Documents/MapleNecrocer_20240623/spine-monogame.dll
----------------------------------------
System.Diagnostics.StackTrace
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    組件版本: 6.0.0.0
    Win32 版本: 6.0.1623.17311
    程式碼基底: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.16/System.Collections.Immutable.dll
----------------------------------------

************** JIT 偵錯 **************



```

**Comment by Elem8100** [comment]
已修復
